services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kb01
    depends_on:
      elasticsearch:
        condition: service_healthy
    # Disable security in Kibana to match Elasticsearch (dev-only)
    command:
      [
        "/usr/local/bin/kibana-docker",
        "--elasticsearch.hosts=http://elasticsearch:9200",
        "--xpack.security.enabled=false"
      ]
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q '\"state\":\"green\"' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30

volumes:
  esdata:
